### PR TITLE
Fetch IPPool labels from VSphereMachineTemplate, for both CP nodes and workers

### LINKED ISSUE #24: IPClaim is associated with incorrect IPPool when multiple IPPools exist within namespace
During deployment of a CAPV cluster, `cluster-api-provider-vsphere-static-ip` consistently associates control plane machine IPClaims with the specified `cluster.x-k8s.io/ip-pool-name`. Worker node MachineDeployments, however are associated with seemingly random IPPools that happen to exist within the same management cluster namespace `default`.

Example of incorrect IPClaim to IPPool association for a MachineDeployment VSphereMachineTemplate below:

IPPool for cluster: `ts-kubeflow-sac-prod` (target of machine template)
```yaml
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: ip-pool-ts-kubeflow-sac-prod
  namespace: default
spec:
  clusterName: ts-kubeflow-sac-prod
...
```

IPPool for cluster: `ts-kubeflow-rck-dev` (different cluster and not the desired target)
```yaml
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: ip-pool-ts-kubeflow-rck-dev
  namespace: default
spec:
  clusterName: ts-kubeflow-rck-dev
...
```

vSphereMachineTemplate used within cluster: `ts-kubeflow-sac-prod`
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: ts-kubeflow-sac-prod-md1-v1
  namespace: default
  labels:
    cluster.x-k8s.io/ip-pool-name: ip-pool-ts-kubeflow-sac-prod
...
```

IPClaim associated with incorrect IPPool at spec/pool/name:
```yaml
apiVersion: ipam.metal3.io/v1alpha1
kind: IPClaim
metadata:
  name: ts-kubeflow-sac-prod-md1-v1-srxbl-0
  namespace: default
spec:
  pool:
    apiVersion: ipam.metal3.io/v1alpha1
    kind: IPPool
    name: ip-pool-ts-kubeflow-rck-dev
    namespace: default
status:
  address:
    name: ts-kubeflow-rck-dev-10-7-5-155
    namespace: default
```

capv-static-ip-controller-manager output:
```log
I1231 01:04:34.235684       1 vspheremachine_controller.go:84] controllers/VSphereMachine "msg"="waiting for machine controller to set ownerRef on VSphereMachine" "vspheremachine"={"Namespace":"default","Name":"ts-kubeflow-sac-prod-md1-v1-srxbl"} 
I1231 01:04:34.381432       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.482634       1 metal3io_ipam.go:116] controllers/VSphereMachine "msg"="IPPool ip-pool-ts-kubeflow-rck-dev is available" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.482814       1 metal3io_ipam.go:34] controllers/VSphereMachine "msg"="get IPAddress ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.583548       1 metal3io_ipam.go:138] controllers/VSphereMachine "msg"="waiting for IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.583633       1 metal3io_ipam.go:46] controllers/VSphereMachine "msg"="allocate IP ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.583675       1 metal3io_ipam.go:168] controllers/VSphereMachine "msg"="create IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.598704       1 metal3io_ipam.go:207] controllers/VSphereMachine "msg"="created IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0, waiting for IPAddress to be available" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.599510       1 vspheremachine_controller.go:162] controllers/VSphereMachine "msg"="waiting for IP address to be available for the VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.599743       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.601003       1 metal3io_ipam.go:116] controllers/VSphereMachine "msg"="IPPool ip-pool-ts-kubeflow-sac-prod is available" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.601322       1 metal3io_ipam.go:34] controllers/VSphereMachine "msg"="get IPAddress ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.601396       1 metal3io_ipam.go:138] controllers/VSphereMachine "msg"="waiting for IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.601431       1 metal3io_ipam.go:46] controllers/VSphereMachine "msg"="allocate IP ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.601472       1 metal3io_ipam.go:168] controllers/VSphereMachine "msg"="create IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.636264       1 metal3io_ipam.go:207] controllers/VSphereMachine "msg"="created IPClaim ts-kubeflow-sac-prod-md1-v1-srxbl-0, waiting for IPAddress to be available" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:04:34.636385       1 vspheremachine_controller.go:162] controllers/VSphereMachine "msg"="waiting for IP address to be available for the VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.603433       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.603535       1 metal3io_ipam.go:116] controllers/VSphereMachine "msg"="IPPool ip-pool-rck-nonprod-corp-nonpci-1 is available" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.603548       1 metal3io_ipam.go:34] controllers/VSphereMachine "msg"="get IPAddress ts-kubeflow-sac-prod-md1-v1-srxbl-0" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.703930       1 vspheremachine_controller.go:170] controllers/VSphereMachine "msg"="static IP for VSphereMachine is ts-kubeflow-rck-dev-10-7-5-155" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.703966       1 vspheremachine_controller.go:174] controllers/VSphereMachine "msg"="assigning IP address 10.7.5.155 to VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.713373       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.714026       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:04.723723       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:06.445087       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:06.464530       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:29.796114       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:05:29.812420       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.317444       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.326339       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.334197       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.348064       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.350894       1 vspheremachine_controller.go:115] controllers/VSphereMachine "msg"="reconcile IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl" 
I1231 01:06:18.378199       1 vspheremachine_controller.go:198] controllers/VSphereMachine "msg"="successfully reconciled IP address for VSphereMachine" "namespace"="default" "vsphereMachine"="ts-kubeflow-sac-prod-md1-v1-srxbl"
```

Is there perhaps some issue with `cluster.x-k8s.io/ip-pool-name` label matching amongst multiple IPPools within the same namespace?

### PR DESCRIPTION
**Pull request by abhinavnagaraj**
What this PR does / why we need it:
This PR fixes the IPPool match labels issue when the IPPool label is missing in the worker VSphereMachine if its not provided in the MachineDeployment. Instead IPPool match labels are retrieved from the corresponding VSphereMachineTemplate, for both CP nodes and workers. The VSphereMachine annotation 'cluster.x-k8s.io/cloned-from-name' is used to fetch the template associated with the VSphereMachine.

Which issue(s) this PR fixes:
Fixes #24

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/25#" title="Author self-approved">abhinavnagaraj</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)~~ [abhinavnagaraj]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: controllers/vspheremachine_controller.go [hunk 1]
```diff
@@ -191,61 +184,35 @@ func (r *VSphereMachineReconciler) reconcileVSphereMachineIPAddress(cluster *cap
...
+	if err := cli.Get(context.Background(), key, vsphereMachineTemplate); err != nil {
+		log.Error(err, "failed to get VSphereMachineTemplate", "VSphereMachineTemplate", vmTemplateName)
+		return labels
+	}
 
-		vmTemplateLabels := util.GetObjLabels(vsphereMachineTemplate)
-		for k, v := range vmTemplateLabels {
-			labels[k] = v
-		}
+	vmTemplateLabels := util.GetObjLabels(vsphereMachineTemplate)
```
Comment (jzhoucliqr) [inline controllers/vspheremachine_controller.go:213]: maybe just directly 
```
return vsphereMachineTemplate.Labels 
```

File: controllers/vspheremachine_controller.go [hunk 2]
```diff
@@ -191,61 +184,35 @@ func (r *VSphereMachineReconciler) reconcileVSphereMachineIPAddress(cluster *cap
...
-func getMatchLabels(cli client.Client, clusterMeta metav1.ObjectMeta, vsphereMachine *infrav1.VSphereMachine, log logr.Logger) map[string]string {
+func (r *VSphereMachineReconciler) getIPPoolMatchLabels(cli client.Client, vSphereMachine *infrav1.VSphereMachine, log logr.Logger) map[string]string {
 	labels := map[string]string{}
 
-	//match labels are an aggregate of VSphereMachine labels & VSphereMachineTemplate labels
-	vmLabels := util.GetObjLabels(vsphereMachine)
-	for k, v := range vmLabels {
-		labels[k] = v
+	//match labels for the IPPool are retrieved from the VSphereMachineTemplate
+	vmTemplateName, ok := vSphereMachine.GetAnnotations()[capi.TemplateClonedFromNameAnnotation]
```
Comment (jzhoucliqr) [inline controllers/vspheremachine_controller.go:200]: when is this annotation added by capi? if recently added, what about existing clusters?

Comment (abhinavnagaraj) [reply controllers/vspheremachine_controller.go:200]: yes, I verified that this was added in capi v0.3.7 - https://github.com/kubernetes-sigs/cluster-api/blob/846ca08db5939e5bf88104b2f34427e7316ee7b9/api/v1alpha3/common_types.go#L43. All clusters using capv-static-ip should be post v0.3.7. I'll update the compatibility matrix in the docs.

File: controllers/vspheremachine_controller.go (hunk 1 above)
Comment (abhinavnagaraj) [reply controllers/vspheremachine_controller.go:213]: Ack

File: controllers/vspheremachine_controller.go [hunk 3]
```diff
@@ -191,64 +188,30 @@ func (r *VSphereMachineReconciler) reconcileVSphereMachineIPAddress(cluster *cap
...
+func (r *VSphereMachineReconciler) getIPPoolMatchLabels(cli client.Client, vSphereMachine *infrav1.VSphereMachine) (map[string]string, error) {
 
-	//match labels are an aggregate of VSphereMachine labels & VSphereMachineTemplate labels
-	vmLabels := util.GetObjLabels(vsphereMachine)
-	for k, v := range vmLabels {
-		labels[k] = v
+	//match labels for the IPPool are retrieved from the VSphereMachineTemplate
+	vmTemplateName, ok := vSphereMachine.GetAnnotations()[capi.TemplateClonedFromNameAnnotation]
+	if !ok {
+		return nil, errors.New(fmt.Sprintf("VSphereMachine %s has no value set in the 'cloned-from-name' annotation", vSphereMachine.Name))
```
Comment (jzhoucliqr) [inline controllers/vspheremachine_controller.go:205]: can use fmt.Errorf()

Comment (abhinavnagaraj) [reply controllers/vspheremachine_controller.go]: Ack
